MKSHELL=/bin/bash

%.bed:Q: %.tmp
	echo "[DEBUG] editing tsv file"
	Rscript --vanilla tsv-editor.R $prereq $target.build \
	&& mv $target.build $target \
	&& rm $prereq

%.tmp:Q: %.tsv
	echo "[DEBUG] removing columns from tsv file"
	cut -f1-4 $prereq > $target.build \
	&& mv $target.build $target
